### ISSUE TITLE
Question regarding spaces after characters

### ISSUE THREAD

**Issue by MatsCraft1** [ArminJo/LCDBigNumbers#1]
Hey, 

I tried changing the library, so there would be an empty column after each character of the “BIG_NUMBERS_FONT_1_COLUMN_2_ROWS_VARIANT_1” but to no avail. Shouldn't it be easy to do this? I saw the void.enableGapBetweenNumbers(); and so on, but how should I use these? They don't seem to work.

I'd be happy about any help.
Thanks in advance!

**Comment by ArminJo** [comment]
Thanks for reporting. 
Please get the latest version from this repo, where the bug of non working enableGapBetweenNumbers() is fixed.
